name: Crowdin Action

on:
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOCKDOORPRO_SYNC_TOKEN }}

      - name: Crowdin action for DockDoorPro
        uses: crowdin/github-action@v2
        with:
          config: 'crowdin.yml'
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: crowdin-localization-dockdoorpro
          create_pull_request: true
          pull_request_title: "chore: sync DockDoorPro localizations with Crowdin"
          commit_message: "chore: sync DockDoorPro localizations with Crowdin"
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKDOORPRO_SYNC_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
